---
- name: Bootstrap Ubuntu_Agent for CI/CD Solar System nodejs App
  hosts: Agent
  become: yes

  vars:
    user_name: "{{ ansible_user }}"

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install basic tools
      apt:
        name:
          - git
          - curl
        state: present

    - name: Install Node.js and npm (from NodeSource)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Add Docker APT repository
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash
      register: docker_repo

    - name: Update APT after adding Docker repo
      apt:
        update_cache: yes
      when: docker_repo.changed

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to docker group
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes


    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash
