
name: Pushing Configuration to self-hosted agent Ansible Pipeline

on:
    push: 
        branches:
            - main
        

jobs:
    push-ansible-config:
        runs-on: self-hosted
        steps:
            - name: Copying files
              uses: actions/checkout@v2
            
            - name: run ansible-playbook
              run: |
                ansible-playbook -i infra/ansible/inventory.ini infra/ansible/config.yml 

