name: Solar System Workflow

on: 
  push:
    branches:
      - main



jobs:  
    unit-testing:
        name: Unit Testing
        runs-on: self-hosted
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Unit Testing
          env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          run: |
            npm install
            npm test
            echo 'test'
          
        - name: Code Coverage
          run: npm run coverage
             
       