name: Solar System Workflow

on: 
  push:
    branches:
      - main
      
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: self-hosted
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Unit Testing
          run: npm test
          
        - name: Code Coverage
          run: npm run coverage
             
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml